-- Table structure for table `message`
CREATE TABLE public.message
(
    message_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    message_subject character varying NOT NULL,
    message_body text NOT NULL,
    message_created timestamp with time zone NOT NULL DEFAULT now(),
    message_to integer NOT NULL,
    message_from integer NOT NULL,
    message_read boolean NOT NULL DEFAULT FALSE,
    message_archived boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT message_pkey PRIMARY KEY (message_id),
    CONSTRAINT fk_message_to FOREIGN KEY (message_to)
        REFERENCES public.account (account_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION,
    CONSTRAINT fk_message_from FOREIGN KEY (message_from)
        REFERENCES public.account (account_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);

ALTER TABLE IF EXISTS public.message
    OWNER to dbcse340;